100 epochs completed in 1.391 hours.
Optimizer stripped from runs/train/yolov8/weights/last.pt, 4.9MB
Optimizer stripped from runs/train/yolov8/weights/best.pt, 4.9MB

Validating runs/train/yolov8/weights/best.pt...
Fusing layers... 
Model Summary: 194 layers, 2308625 parameters, 0 gradients, 5.4 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 13/13 [00:03<00:00,  3.26it/s]              
                 all        404        858      0.915      0.928      0.967      0.617
          closed_eye        404        161      0.894      0.944      0.965      0.544
        closed_mouth        404        172      0.895      0.844      0.946      0.629
            open_eye        404        400      0.931       0.99      0.987      0.585
          open_mouth        404        125      0.941      0.936      0.968      0.711
Results saved to runs/train/yolov8

weights: weight/yolov7-tiny.pt
cfg: yolo/YOLOv8.yaml
data: mydata/data.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 100
loss: origin
auxotaloss: false
otaloss: origin
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 4
project: runs/train
name: yolov8
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 50
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolov8
