weights: weight/yolov7-tiny.pt
cfg: yolov7/FEY-YOLOv7.yaml
data: mydata/data.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 100
loss: origin
auxotaloss: false
otaloss: origin
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 4
project: runs/train
name: '0'
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 50
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/0
